controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    kai_controller: 
      type: joint_trajectory_controller/JointTrajectoryController


kai_controller:
  ros__parameters:
    joints:
      - baseyaw_joint
      - baseroll_joint
      - outarm_joint

    command_interfaces:
      - position
    state_interfaces:
      - position