<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:include filename="$(find robot_description)/urdf/inertial_macros.xacro"/>

    <!-- COLORS -->

    <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!-- VARIABLES -->

    <xacro:property name="middle_link_length" value="9.0" />
    <xacro:property name="middle_link_width" value="0.2" />
    <xacro:property name="middle_link_height" value="0.2" />

    <xacro:property name="leg_length" value="3.2" />
    <xacro:property name="leg_width" value="0.2" />
    <xacro:property name="leg_height" value="0.2" />

    <xacro:property name="slider_fb_link_length" value="3.5" />
    <xacro:property name="slider_fb_link_width" value="0.2" />
    <xacro:property name="slider_fb_link_height" value="0.2" />

    <xacro:property name="slider_ud_link_length" value="${leg_length-leg_length*0.05}" />
    <xacro:property name="slider_ud_link_width" value="0.1" />
    <xacro:property name="slider_ud_link_height" value="0.1" />

    <!-- WORLD LINK -->

    <link name="world"/>

    <!-- BASE LEFT -->

    <link name="middle_link_a">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${middle_link_length} ${middle_link_width} ${middle_link_width}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${middle_link_length} ${middle_link_width} ${middle_link_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${middle_link_length}" y="${middle_link_width}" z="${middle_link_width}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="middle_link_a_world_joint" type="fixed">
        <parent link="world"/>
        <child link="middle_link_a"/>
        <origin xyz="0.0 ${slider_fb_link_length/2+middle_link_width/2} ${leg_length+leg_height/2}"/>
    </joint>

    <link name="left_leg_link_a">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${leg_height}" y="${leg_width}" z="${leg_length}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_leg_link_a_world_joint" type="fixed">
        <parent link="world"/>
        <child link="left_leg_link_a"/>
        <origin xyz="-${middle_link_length/2-leg_width/2} ${slider_fb_link_length/2+leg_width/2} ${leg_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="right_leg_link_a">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${leg_height}" y="${leg_width}" z="${leg_length}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_leg_link_a_world_joint" type="fixed">
        <parent link="world"/>
        <child link="right_leg_link_a"/>
        <origin xyz="${middle_link_length/2-leg_width/2} ${slider_fb_link_length/2+leg_width/2} ${leg_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- BASE RIGHT -->

    <link name="middle_link_b">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${middle_link_length} ${middle_link_width} ${middle_link_width}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${middle_link_length} ${middle_link_width} ${middle_link_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${middle_link_length}" y="${middle_link_width}" z="${middle_link_width}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="middle_link_b_world_joint" type="fixed">
        <parent link="world"/>
        <child link="middle_link_b"/>
        <origin xyz="0.0 -${slider_fb_link_length/2+middle_link_width/2} ${leg_length+leg_height/2}"/>
    </joint>

    <link name="left_leg_link_b">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${leg_height}" y="${leg_width}" z="${leg_length}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_leg_link_b_world_joint" type="fixed">
        <parent link="world"/>
        <child link="left_leg_link_b"/>
        <origin xyz="-${middle_link_length/2-leg_width/2} -${slider_fb_link_length/2+leg_width/2} ${leg_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="right_leg_link_b">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${leg_height} ${leg_width} ${leg_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${leg_height}" y="${leg_width}" z="${leg_length}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_leg_link_b_world_joint" type="fixed">
        <parent link="world"/>
        <child link="right_leg_link_b"/>
        <origin xyz="${middle_link_length/2-leg_width/2} -${slider_fb_link_length/2+leg_width/2} ${leg_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- FB SLIDER LINK -->

    <link name="slider_fb_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${slider_fb_link_width} ${slider_fb_link_length} ${slider_fb_link_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${slider_fb_link_width} ${slider_fb_link_length} ${slider_fb_link_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${slider_fb_link_width}" y="${slider_fb_link_length}" z="${slider_fb_link_height}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="slider_fb_link_middle_link_a_joint" type="prismatic">
        <parent link="middle_link_a"/>
        <child link="slider_fb_link"/>
        <origin xyz="${middle_link_length/2-slider_fb_link_width/2} -${slider_fb_link_length/2+middle_link_width/2} 0.0"/>
        <axis xyz="-1 0 0"/>
        <limit lower="0" upper="${middle_link_length-slider_fb_link_width}" velocity="100" effort="100"/> 
    </joint>

    <!-- VIRTUAL LINK -->
    <!-- this is required to be able to provide translational motion over two axis -->

   <link name="virtual_link">
  <inertial>
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
    <mass value="1.0"/> <!-- Adjust the mass as necessary -->
    <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/> <!-- Minimal inertia -->
  </inertial>
</link>


    <joint name="virtual_link_slider_fb_link_joint" type="prismatic">
        <parent link="slider_fb_link"/>
        <child link="virtual_link"/>
        <origin xyz="-${slider_fb_link_width/2+slider_ud_link_width/2} 0.0 ${slider_ud_link_length/2}"/>
        <axis xyz="0 0 -1"/>
        <limit lower="${slider_fb_link_height/2}" upper="${slider_ud_link_length}" velocity="100" effort="100"/> 
    </joint>

    <!-- UD SLIDER LINK -->

    <link name="slider_ud_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${slider_ud_link_height} ${slider_ud_link_width} ${slider_ud_link_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${slider_ud_link_height} ${slider_ud_link_width} ${slider_ud_link_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="${slider_ud_link_height}" y="${slider_ud_link_width}" z="${slider_ud_link_length}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="sslider_ud_link_virtual_link_joint" type="prismatic">
        <parent link="virtual_link"/>
        <child link="slider_ud_link"/>
        <axis xyz="0 -1 0"/>
        <limit lower="-${slider_fb_link_length/2-slider_fb_link_width/2}" upper="${slider_fb_link_length/2-slider_fb_link_width/2}" velocity="100" effort="100"/> 
    </joint>

    <link name="virtual_gripper_link"/>

    <joint name="virtual_gripper_link_sslider_ud_link_joint" type="fixed">
        <parent link="slider_ud_link"/>
        <child link="virtual_gripper_link"/>
        <origin xyz="0.0 0.0 -${slider_ud_link_length/2}"/>
    </joint>
    

</robot>