# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - kai_arm_controller

  kai_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - baseyaw_joint
      - baseroll_joint
      - outarm_joint
    action_ns: follow_joint_trajectory
    default: true