# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kai_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kai_arm_controller:
  ros__parameters:
    joints:
      - baseyaw_joint
      - baseroll_joint
      - outarm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position